alias v=nvim
alias vim=nvim
alias q="exit"
alias g="git"
alias gs="git status"
alias bashrc="source ~/.bashrc"
alias zshrc="source ~/.zshrc"
alias ll="ls -la"
alias run="screen -d -m"
alias p="sudo pacman"
alias neofetch="clear;neofetch;truecolor-test"
alias startmpd="mpd; run mpDris2; ncmpcpp"
alias tas="tmux_cond_attach"
