alias v=nvim
alias vim=nvim
alias dotfiles="cd ~/repos/dotfiles"
alias web="cd ~/repos/website"
alias q="exit"
alias g="git"
alias gs="git status"
alias bashrc="source ~/.bashrc"
alias ls="ls -la"
alias rweb="cd ~/repos/website; bundle exec jekyll serve --livereload"
alias run="screen -d -m"
alias p="sudo pacman"
alias neofetch="clear;neofetch;truecolor-test"
alias startmpd="mpd; run mpDris2; ncmpcpp"
